// Copyright 2024 Accenture.

#pragma once

namespace bios
{

enum
{
    _ADCCHANNEL0 = 0,
    _ADCCHANNEL1,
    _ADCCHANNEL2,
    _ADCCHANNEL3,
    _ADCCHANNEL4,
    _ADCCHANNEL5,
    _ADCCHANNEL6,
    _ADCCHANNEL7,
    _ADCCHANNEL8,
    _ADCCHANNEL9,
    _ADCCHANNEL10,
    _ADCCHANNEL11,
    _ADCCHANNEL12,
    _ADCCHANNEL13,
    _ADCCHANNEL14,
    _ADCCHANNEL15,
    _ADCINTERNAL0 = 21,
    _ADCINTERNAL1,
    _ADCINTERNAL2,
    _BANDGAP      = 27,
    _ADCINTERNAL3 = 28,
    _VREFSH,
    _VREFS,
    _ADCCHANNEL16 = 32,
    _ADCCHANNEL17,
    _ADCCHANNEL18,
    _ADCCHANNEL19,
    _ADCCHANNEL20,
    _ADCCHANNEL21,
    _ADCCHANNEL22,
    _ADCCHANNEL23,
    _ADCCHANNEL24,
    _ADCCHANNEL25,
    _ADCCHANNEL26,
    _ADCCHANNEL27,
    _ADCCHANNEL28,
    _ADCCHANNEL29,
    _ADCCHANNEL30,
    _ADCCHANNEL31
};

}
