// Copyright 2024 Accenture.

// IGNORE_INCLUDE_GUARD_CHECK

#if defined(BSP_IO_PIN_CONFIGURATION) && (BSP_IO_PIN_CONFIGURATION == 1)

Io::PinConfiguration const Io::fPinConfiguration[Io::NUMBER_OF_IOS] = {
    // clang-format off

    /* 00  */ {_PORTA_, PA0, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, GPIO},
    /* 01  */ {_PORTA_, PA1, _OUT, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, (uint32_t) GPIO | (uint32_t) STRENGTH_ON},
    /* 02  */ {_PORTA_, PA2, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 03  */ {_PORTA_, PA3, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 04  */ {_PORTA_, PA4, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 05  */ {_PORTA_, PA5, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 06  */ {_PORTA_, PA6, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 07  */ {_PORTA_, PA7, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 08  */ {_PORTA_, PA8, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 09  */ {_PORTA_, PA9, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 10  */ {_PORTA_, PA10, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 11  */ {_PORTA_, PA11, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 12  */ {_PORTA_, PA12, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 13  */ {_PORTA_, PA13, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 14  */ {_PORTA_, PA14, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 15  */ {_PORTA_, PA15, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 16  */ {_PORTA_, PA16, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 17  */ {_PORTA_, PA17, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 18  */ {_PORTA_, PA18, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 19  */ {_PORTA_, PA19, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 20  */ {_PORTA_, PA20, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 21  */ {_PORTA_, PA21, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 22  */ {_PORTA_, PA22, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 23  */ {_PORTA_, PA23, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 24  */ {_PORTA_, PA24, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 25  */ {_PORTA_, PA25, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 26  */ {_PORTA_, PA26, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 27  */ {_PORTA_, PA27, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 28  */ {_PORTA_, PA28, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 29  */ {_PORTA_, PA29, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 30  */ {_PORTA_, PA30, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 31  */ {_PORTA_, PA31, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},

    /* 32  */ {_PORTB_, PB0, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 33  */ {_PORTB_, PB1, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 34  */ {_PORTB_, PB2, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 35  */ {_PORTB_, PB3, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 36  */ {_PORTB_, PB4, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 37  */ {_PORTB_, PB5, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 38  */ {_PORTB_, PB6, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 39  */ {_PORTB_, PB7, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 40  */ {_PORTB_, PB8, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 41  */ {_PORTB_, PB9, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 42  */ {_PORTB_, PB10, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 43  */ {_PORTB_, PB11, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 44  */ {_PORTB_, PB12, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 45  */ {_PORTB_, PB13, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 46  */ {_PORTB_, PB14, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 47  */ {_PORTB_, PB15, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 48  */ {_PORTB_, PB16, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 49  */ {_PORTB_, PB17, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 50  */ {_PORTB_, PB18, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 51  */ {_PORTB_, PB19, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 52  */ {_PORTB_, PB20, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 53  */ {_PORTB_, PB21, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 54  */ {_PORTB_, PB22, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 55  */ {_PORTB_, PB23, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 56  */ {_PORTB_, PB24, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 57  */ {_PORTB_, PB25, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 58  */ {_PORTB_, PB26, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 59  */ {_PORTB_, PB27, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 60  */ {_PORTB_, PB28, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 61  */ {_PORTB_, PB29, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 62  */ {_PORTB_, PB30, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 63  */ {_PORTB_, PB31, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},

    /* 64  */ {_PORTC_, PC0, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, ALT3},
    /* 65  */ {_PORTC_, PC1, _OUT, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, (uint32_t) ALT3 | (uint32_t) STRENGTH_ON},
    /* 66  */ {_PORTC_, PC2, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 67  */ {_PORTC_, PC3, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 68  */ {_PORTC_, PC4, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 69  */ {_PORTC_, PC5, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 70  */ {_PORTC_, PC6, _IN, 0, ALT2},
    /* 71  */ {_PORTC_, PC7, _OUT, 0, (uint32_t) ALT2 | (uint32_t) STRENGTH_ON},
    /* 72  */ {_PORTC_, PC8, _IN, 0, ALT2},
    /* 73  */ {_PORTC_, PC9, _OUT, 0, (uint32_t) ALT2 | (uint32_t) STRENGTH_ON},
    /* 74  */ {_PORTC_, PC10, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 75  */ {_PORTC_, PC11, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 76  */ {_PORTC_, PC12, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, GPIO},
    /* 77  */ {_PORTC_, PC13, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 78  */ {_PORTC_, PC14, _OUT, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, (uint32_t) GPIO | (uint32_t) STRENGTH_ON},
    /* 79  */ {_PORTC_, PC15, _OUT, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, (uint32_t) ALT3 | (uint32_t) STRENGTH_ON},
    /* 80  */ {_PORTC_, PC16, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 81  */ {_PORTC_, PC17, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 82  */ {_PORTC_, PC18, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 83  */ {_PORTC_, PC19, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 84  */ {_PORTC_, PC20, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 85  */ {_PORTC_, PC21, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 86  */ {_PORTC_, PC22, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 87  */ {_PORTC_, PC23, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 88  */ {_PORTC_, PC24, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 89  */ {_PORTC_, PC25, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 90  */ {_PORTC_, PC26, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 91  */ {_PORTC_, PC27, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 92  */ {_PORTC_, PC28, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 93  */ {_PORTC_, PC29, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 94  */ {_PORTC_, PC30, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 95  */ {_PORTC_, PC31, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},

    /* 96  */ {_PORTD_, PD0, _OUT, 0, (uint32_t) ALT3 | (uint32_t) (uint32_t) STRENGTH_ON | (uint32_t) PULLUP},
    /* 97  */ {_PORTD_, PD1, _IN, 0, (uint32_t) ALT3 | (uint32_t) PULLUP},
    /* 98  */ {_PORTD_, PD2, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 99  */ {_PORTD_, PD3, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 100  */ {_PORTD_, PD4, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 101  */ {_PORTD_, PD5, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 102  */ {_PORTD_, PD6, _IN, 0, ALT2},
    /* 103  */ {_PORTD_, PD7, _OUT, 0, (uint32_t) ALT2 | (uint32_t) STRENGTH_ON},
    /* 104  */ {_PORTD_, PD8, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 105  */ {_PORTD_, PD9, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 106  */ {_PORTD_, PD10, _OUT, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, (uint32_t) GPIO | (uint32_t) (uint32_t) STRENGTH_ON | (uint32_t) PULLUP},
    /* 107  */ {_PORTD_, PD11, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 108  */ {_PORTD_, PD12, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 109  */ {_PORTD_, PD13, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 110  */ {_PORTD_, PD14, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 111  */ {_PORTD_, PD15, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 112  */ {_PORTD_, PD16, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 113  */ {_PORTD_, PD17, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 114  */ {_PORTD_, PD18, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 115  */ {_PORTD_, PD19, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 116  */ {_PORTD_, PD20, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 117  */ {_PORTD_, PD21, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 118  */ {_PORTD_, PD22, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 119  */ {_PORTD_, PD23, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 120  */ {_PORTD_, PD24, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 121  */ {_PORTD_, PD25, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 122  */ {_PORTD_, PD26, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 123  */ {_PORTD_, PD27, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 124  */ {_PORTD_, PD28, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 125  */ {_PORTD_, PD29, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 126  */ {_PORTD_, PD30, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 127  */ {_PORTD_, PD31, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},

    /* 128  */ {_PORTE_, PE0, _OUT, 0, (uint32_t) ALT5 | (uint32_t) STRENGTH_ON},
    /* 129  */ {_PORTE_, PE1, _OUT, 0, (uint32_t) GPIO | (uint32_t) (uint32_t) STRENGTH_ON | (uint32_t) PULLUP},
    /* 130  */ {_PORTE_, PE2, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 131  */ {_PORTE_, PE3, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 132  */ {_PORTE_, PE4, _IN, 0, ALT5},
    /* 133  */ {_PORTE_, PE5, _OUT, 0, (uint32_t) ALT5 | (uint32_t) STRENGTH_ON},
    /* 134  */ {_PORTE_, PE6, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 135  */ {_PORTE_, PE7, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 136  */ {_PORTE_, PE8, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 137  */ {_PORTE_, PE9, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 138  */ {_PORTE_, PE10, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 139  */ {_PORTE_, PE11, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 140  */ {_PORTE_, PE12, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 141  */ {_PORTE_, PE13, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 142  */ {_PORTE_, PE14, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 143  */ {_PORTE_, PE15, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 144  */ {_PORTE_, PE16, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 145  */ {_PORTE_, PE17, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 146  */ {_PORTE_, PE18, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 147  */ {_PORTE_, PE19, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 148  */ {_PORTE_, PE20, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 149  */ {_PORTE_, PE21, _OUT, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, (uint32_t) GPIO | (uint32_t) STRENGTH_ON},
    /* 150  */ {_PORTE_, PE22, _OUT, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, (uint32_t) ALT2 | (uint32_t) STRENGTH_ON},
    /* 151  */ {_PORTE_, PE23, _OUT, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, (uint32_t) ALT2 | (uint32_t) STRENGTH_ON},
    /* 152  */ {_PORTE_, PE24, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 153  */ {_PORTE_, PE25, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 154  */ {_PORTE_, PE26, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},
    /* 155  */ {_PORTE_, PE27, _IN, (uint8_t) FILTER_ACTIVE | (uint8_t) FILTER_TICK1, PINDISABLE},

    // clang-format on
};

#else

enum PinId
{
    /* 00 */ EVAL_DI_1,
    /* 01 */ EVAL_DO_1,
    /* 02 */ EVAL_AI_1,
    /* 03 */ PIN_A_3,
    /* 04 */ PIN_A_4,
    /* 05 */ PIN_A_5,
    /* 06 */ PIN_A_6,
    /* 07 */ PIN_A_7,
    /* 08 */ PIN_A_8,
    /* 09 */ PIN_A_9,
    /* 10 */ PIN_A_10,
    /* 11 */ PIN_A_11,
    /* 12 */ PIN_A_12,
    /* 13 */ PIN_A_13,
    /* 14 */ PIN_A_14,
    /* 15 */ PIN_A_15,
    /* 16 */ PIN_A_16,
    /* 17 */ PIN_A_17,
    /* 18 */ PIN_A_18,
    /* 19 */ PIN_A_19,
    /* 20 */ PIN_A_20,
    /* 21 */ PIN_A_21,
    /* 22 */ PIN_A_22,
    /* 23 */ PIN_A_23,
    /* 24 */ PIN_A_24,
    /* 25 */ PIN_A_25,
    /* 26 */ PIN_A_26,
    /* 27 */ PIN_A_27,
    /* 28 */ PIN_A_28,
    /* 29 */ PIN_A_29,
    /* 30 */ PIN_A_30,
    /* 31 */ PIN_A_31,

    /* 32 */ PIN_B_0,
    /* 33 */ PIN_B_1,
    /* 34 */ PIN_B_2,
    /* 35 */ PIN_B_3,
    /* 36 */ PIN_B_4,
    /* 37 */ PIN_B_5,
    /* 38 */ PIN_B_6,
    /* 39 */ PIN_B_7,
    /* 40 */ PIN_B_8,
    /* 41 */ PIN_B_9,
    /* 42 */ PIN_B_10,
    /* 43 */ PIN_B_11,
    /* 44 */ PIN_B_12,
    /* 45 */ PIN_B_13,
    /* 46 */ PIN_B_14,
    /* 47 */ PIN_B_15,
    /* 48 */ PIN_B_16,
    /* 49 */ PIN_B_17,
    /* 50 */ PIN_B_18,
    /* 51 */ PIN_B_19,
    /* 52 */ PIN_B_20,
    /* 53 */ PIN_B_21,
    /* 54 */ PIN_B_22,
    /* 55 */ PIN_B_23,
    /* 56 */ PIN_B_24,
    /* 57 */ PIN_B_25,
    /* 58 */ PIN_B_26,
    /* 59 */ PIN_B_27,
    /* 60 */ PIN_B_28,
    /* 61 */ PIN_B_29,
    /* 62 */ PIN_B_30,
    /* 63 */ PIN_B_31,

    /* 64 */ SPI2_MISO,
    /* 65 */ SPI2_MOSI,
    /* 66 */ PIN_C_2,
    /* 67 */ PIN_C_3,
    /* 68 */ PIN_C_4,
    /* 69 */ PIN_C_5,
    /* 70 */ UART1_RX,
    /* 71 */ UART1_TX,
    /* 72 */ LIN1_Rx,
    /* 73 */ LIN1_Tx,
    /* 74 */ PIN_C_10,
    /* 75 */ PIN_C_11,
    /* 76 */ EVAL_SW3,
    /* 77 */ PIN_C_13,
    /* 78 */ SPI2_CSN0,
    /* 79 */ SPI2_SCK,
    /* 80 */ PIN_C_16,
    /* 81 */ PIN_C_17,
    /* 82 */ EVAL_POTI_ADC,
    /* 83 */ EVAL_ADC,
    /* 84 */ PIN_C_20,
    /* 85 */ PIN_C_21,
    /* 86 */ PIN_C_22,
    /* 87 */ PIN_C_23,
    /* 88 */ PIN_C_24,
    /* 89 */ PIN_C_25,
    /* 90 */ PIN_C_26,
    /* 91 */ PIN_C_27,
    /* 92 */ PIN_C_28,
    /* 93 */ PIN_C_29,
    /* 94 */ PIN_C_30,
    /* 95 */ PIN_C_31,

    /* 96 */ SPI1_SCK,
    /* 97 */ SPI1_MISO,
    /* 98 */ PIN_D_2,
    /* 99 */ PIN_D_3,
    /* 100 */ PIN_D_4,
    /* 101 */ PIN_D_5,
    /* 102 */ UART_RX,
    /* 103 */ UART_TX,
    /* 104 */ PIN_D_8,
    /* 105 */ PIN_D_9,
    /* 106 */ SPI1_CSN1,
    /* 107 */ PIN_D_11,
    /* 108 */ PIN_D_12,
    /* 109 */ PIN_D_13,
    /* 110 */ PIN_D_14,
    /* 111 */ PIN_D_15,
    /* 112 */ PIN_D_16,
    /* 113 */ PIN_D_17,
    /* 114 */ PIN_D_18,
    /* 115 */ PIN_D_19,
    /* 116 */ PIN_D_20,
    /* 117 */ PIN_D_21,
    /* 118 */ PIN_D_22,
    /* 119 */ PIN_D_23,
    /* 120 */ PIN_D_24,
    /* 121 */ PIN_D_25,
    /* 122 */ PIN_D_26,
    /* 123 */ PIN_D_27,
    /* 124 */ PIN_D_28,
    /* 125 */ PIN_D_29,
    /* 126 */ PIN_D_30,
    /* 127 */ PIN_D_31,

    /* 128 */ SPI1_MOSI,
    /* 129 */ SPI1_CSN0,
    /* 130 */ PIN_E_2,
    /* 131 */ PIN_E_3,
    /* 132 */ canRx,
    /* 133 */ canTx,
    /* 134 */ PIN_E_6,
    /* 135 */ PIN_E_7,
    /* 136 */ PIN_E_8,
    /* 137 */ PIN_E_9,
    /* 138 */ PIN_E_10,
    /* 139 */ PIN_E_11,
    /* 140 */ PIN_E_12,
    /* 141 */ PIN_E_13,
    /* 142 */ PIN_E_14,
    /* 143 */ PIN_E_15,
    /* 144 */ PIN_E_16,
    /* 145 */ PIN_E_17,
    /* 146 */ PIN_E_18,
    /* 147 */ PIN_E_19,
    /* 148 */ PIN_E_20,
    /* 149 */ EVAL_LED_RED,
    /* 150 */ EVAL_LED_GREEN,
    /* 151 */ EVAL_LED_BLUE,
    /* 152 */ PIN_E_24,
    /* 153 */ PIN_E_25,
    /* 154 */ PIN_E_26,
    /* 155 */ PIN_E_27,

    /* xx */ NUMBER_OF_INPUTS_AND_OUTPUTS,
    /* xx */ PORT_UNAVAILABLE = NUMBER_OF_INPUTS_AND_OUTPUTS,
};

#endif /* BSP_IO_PIN_CONFIGURATION == 1 */
