"""
Clang-tidy Checker
==================
This script runs the llvm helper tool run-clang-tidy on all compilation units specified by compile_commands.json,
except those in test, 3rdparty, and mock directories. It exports the findings to a specified YAML file and generates
a report with the number of findings per diagnostic which is printed to stdout.

Arguments:
    build_directory: Path to the directory containing compile_commands.json generated by CMake
    output_file: Path to the output YAML file where clang-tidy findings will be stored

Usage:
    python3 .ci/clang-tidy.py <build_directory> <output_file>
"""

import subprocess
import sys
import yaml
from pathlib import Path
from collections import Counter


def count_findings(file_name: str) -> int:
    """
    Reads the YAML file generated by clang-tidy and counts the number of findings per diagnostic name.

    Args:
        file_name: Path to the YAML file containing clang-tidy findings

    Returns:
        Total number of findings
    """

    with open(file_name, "r") as f:
        data = yaml.safe_load(f)

    # Count findings per diagnostic name
    counter = Counter()

    for diagnostic in data.get("Diagnostics", []):
        diagnostic_name = diagnostic.get("DiagnosticName")
        if diagnostic_name:
            counter[diagnostic_name] += 1

    # Sort by count (descending) and then by name
    sorted_findings = sorted(counter.items(), key=lambda x: (-x[1], x[0]))

    # Print the report
    total_findings = sum(counter.values())
    print("Clang-Tidy Findings Report")
    print("=" * 60)
    print(f"\nTotal unique checks: {len(sorted_findings)}")
    print(f"Total findings: {total_findings}")
    print("\nFindings per check:")
    print("-" * 60)

    for check_name, count in sorted_findings:
        print(f"{check_name}: {count}")

    return total_findings


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Error: Missing required arguments.", file=sys.stderr)
        print(
            "Usage: python3 .ci/clang-tidy.py <build_directory> <output_file>",
            file=sys.stderr,
        )
        sys.exit(1)

    BUILD_DIR = Path(sys.argv[1])
    FINDINGS_FILE = Path(sys.argv[2])

    subprocess.run(
        [
            "run-clang-tidy-17",
            "-p",
            f"{BUILD_DIR.as_posix()}",
            "-quiet",
            "-export-fixes",
            f"{FINDINGS_FILE.as_posix()}",
            "^(?!.*(3rdparty)).*",
        ]
    )
    number_of_findings = count_findings(f"{FINDINGS_FILE.as_posix()}")
    if number_of_findings != 0:
        sys.exit(1)
    else:
        sys.exit(0)
