#!/usr/bin/env python3
from shutil import which
import subprocess
import sys


def get_correct_clang_format():
    path = which("clang-format-17")
    if path:
        return path

    if which("clang-format") is None:
        raise Exception("no clang-format found")

    result = subprocess.run(
        ["clang-format", "--version"], capture_output=True, text=True, check=True
    )
    version = result.stdout.strip().split()[-1]
    if version.split(".")[0] != "17":
        raise Exception(f"clang-format version 17 required. Found ${version}")

    return "clang-format"


def main():
    clang_format = get_correct_clang_format()
    subprocess.run([clang_format] + sys.argv[1:])


if __name__ == "__main__":
    main()
