name: Build Sphinx Documentation

on: [workflow_call, pull_request]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build the docker image
      run: |
          docker build -f docker/Dockerfile.docs -t docs .

    - name: Run the sphinx-docs.py inside the docker container
      run: |
          docker run --rm -v "$PWD:/home/jenkins" -w /home/jenkins --user $(id -u):4996 docs python3 .ci/sphinx-docs.py

    - name: Run the sphinx-docs.py inside the docker container
      run: |
          mv doc/build/html sphinx_docs
          zip -r sphinx_docs.zip sphinx_docs

    - name: Upload sphinx_docs
      uses: actions/upload-artifact@v4
      with:
        name: sphinx_docs
        path: sphinx_docs.zip
